version: "5"
services:
  db:
    image: mongo:latest
    container_name: "mongo_db"
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    container_name: "spring_backend"
    ports:
      - "8080:8080"
    links:
      - db
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: "react-frontend"
    ports:
      - "3000:3000"
    links:
      - backend